05:44:12 | ERROR | Error:
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           │    └ <function MemoryObjectReceiveStream.receive_nowait at 0x7f5e16b41870>
           └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
          └ <class 'anyio.WouldBlock'>

anyio.WouldBlock


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
                    │           └ <function MemoryObjectReceiveStream.receive at 0x7f5e16b41900>
                    └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
          └ <class 'anyio.EndOfStream'>

anyio.EndOfStream


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 9
               └ <function _main at 0x7f5e17c92440>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f5e17e656c0>
           └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f5e17e64d30>
    └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f5e17ca61d0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
    │    └ <function subprocess_started at 0x7f5e172c53f0>
    └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f5e17ca6230>>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
           │       │   │    └ <function Server.serve at 0x7f5e172c4700>
           │       │   └ <uvicorn.server.Server object at 0x7f5e17ca6230>
           │       └ <function run at 0x7f5e17c9d6c0>
           └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f5e163061f0>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f5e176ced40>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f5e176cecb0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f5e176d0820>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1899, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f5e17c341f0>
    └ <Handle <TaskStepMethWrapper object at 0x7f5e148d0bb0>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f5e148d0bb0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f5e148d0bb0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f5e148d0bb0>()>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f5e1635d600>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e148d02b0>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e148d02b0>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
                 │    └ <fastapi.applications.FastAPI object at 0x7f5e172f6350>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f5e1635d600>
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e148d02b0>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e148d02b0>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e148d02b0>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e148d02b0>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f5e1667aef0>
          └ <fastapi.applications.FastAPI object at 0x7f5e172f6350>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f5e15df09d0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e148d02b0>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f5e1667aef0>
> File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
                     │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f5e15df0af0>
                     │    │             └ <starlette.requests.Request object at 0x7f5e1547e5f0>
                     │    └ <function log_middle at 0x7f5e16321bd0>
                     └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>

  File "/app/NBDapp/api_views.py", line 47, in log_middle
    response = await call_next(request)
                     │         └ <starlette.requests.Request object at 0x7f5e1547e5f0>
                     └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f5e15df0af0>

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
          └ AttributeError("'NoneType' object has no attribute 'ready_suggestions'")
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
          │    │   │      │       │        │           └ <function MemoryObjectSendStream.send at 0x7f5e16b42050>
          │    │   │      │       │        └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...
          │    │   │      │       └ <property object at 0x7f5e169ae980>
          │    │   │      └ <starlette.requests.Request object at 0x7f5e1547e5f0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f5e1667ba00>
          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e15e0bf40>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e15440c10>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f5e1667b8b0>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f5e1667ba00>
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e15e0bf40>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e15440c10>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <fastapi.routing.APIRouter object at 0x7f5e172f5c60>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f5e1667b8b0>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e15e0bf40>
          │     │      │      └ <function set_body.<locals>.receive at 0x7f5e15440c10>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │     └ <function Route.handle at 0x7f5e167fe680>
          └ <fastapi.routing.APIRoute object at 0x7f5e16675630>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e15e0bf40>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e15440c10>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <function request_response.<locals>.app at 0x7f5e16350550>
          └ <fastapi.routing.APIRoute object at 0x7f5e16675630>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7f5e148d2020>
                     └ <function get_request_handler.<locals>.app at 0x7f5e163504c0>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x7f5e167fd480>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'tg_id': 511979961}
                 │         └ <function next_sug at 0x7f5e16350430>
                 └ <fastapi.dependencies.models.Dependant object at 0x7f5e16675de0>

  File "/app/NBDapp/api_views.py", line 475, in next_sug
    if r_sug.ready_suggestions.index(r_sug.sended_suggestion)+1 < len(r_sug.ready_suggestions):
       │                             │                                └ None
       │                             └ None
       └ None

AttributeError: 'NoneType' object has no attribute 'ready_suggestions'
11:44:14 | ERROR | Error:
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           │    └ <function MemoryObjectReceiveStream.receive_nowait at 0x7f5e16b41870>
           └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
          └ <class 'anyio.WouldBlock'>

anyio.WouldBlock


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
                    │           └ <function MemoryObjectReceiveStream.receive at 0x7f5e16b41900>
                    └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
          └ <class 'anyio.EndOfStream'>

anyio.EndOfStream


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 9
               └ <function _main at 0x7f5e17c92440>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f5e17e656c0>
           └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f5e17e64d30>
    └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f5e17ca61d0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
    │    └ <function subprocess_started at 0x7f5e172c53f0>
    └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f5e17ca6230>>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
           │       │   │    └ <function Server.serve at 0x7f5e172c4700>
           │       │   └ <uvicorn.server.Server object at 0x7f5e17ca6230>
           │       └ <function run at 0x7f5e17c9d6c0>
           └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f5e163061f0>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f5e176ced40>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f5e176cecb0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f5e176d0820>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1899, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f5e17c341f0>
    └ <Handle <TaskStepMethWrapper object at 0x7f5e154b7280>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f5e154b7280>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f5e154b7280>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f5e154b7280>()>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f5e1635d600>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e153e9630>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e153e9630>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
                 │    └ <fastapi.applications.FastAPI object at 0x7f5e172f6350>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f5e1635d600>
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e153e9630>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e153e9630>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e153e9630>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e153e9630>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f5e1667aef0>
          └ <fastapi.applications.FastAPI object at 0x7f5e172f6350>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f5e149ce050>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e153e9630>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f5e1667aef0>
> File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
                     │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f5e149ce8c0>
                     │    │             └ <starlette.requests.Request object at 0x7f5e14a729b0>
                     │    └ <function log_middle at 0x7f5e16321bd0>
                     └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>

  File "/app/NBDapp/api_views.py", line 47, in log_middle
    response = await call_next(request)
                     │         └ <starlette.requests.Request object at 0x7f5e14a729b0>
                     └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f5e149ce8c0>

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
          └ IntegrityError(UniqueViolationError('duplicate key value violates unique constraint "users_tg_pkey"'))
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
          │    │   │      │       │        │           └ <function MemoryObjectSendStream.send at 0x7f5e16b42050>
          │    │   │      │       │        └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...
          │    │   │      │       └ <property object at 0x7f5e169ae980>
          │    │   │      └ <starlette.requests.Request object at 0x7f5e14a729b0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f5e1667ba00>
          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e149cdfc0>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e149cea70>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f5e1667b8b0>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f5e1667ba00>
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e149cdfc0>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e149cea70>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <fastapi.routing.APIRouter object at 0x7f5e172f5c60>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f5e1667b8b0>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e149cdfc0>
          │     │      │      └ <function set_body.<locals>.receive at 0x7f5e149cea70>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │     └ <function Route.handle at 0x7f5e167fe680>
          └ <fastapi.routing.APIRoute object at 0x7f5e16675f90>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e149cdfc0>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e149cea70>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <function request_response.<locals>.app at 0x7f5e16323010>
          └ <fastapi.routing.APIRoute object at 0x7f5e16675f90>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7f5e154b6d10>
                     └ <function get_request_handler.<locals>.app at 0x7f5e16322f80>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x7f5e167fd480>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user': {'id': 180148319, 'is_bot': False, 'first_name': 'ДЛ', 'last_name': None, 'username': 'djamka00', 'language_code': '...
                 │         └ <function user_create at 0x7f5e16322ef0>
                 └ <fastapi.dependencies.models.Dependant object at 0x7f5e16674250>

  File "/app/NBDapp/api_views.py", line 163, in user_create
    usermy = await User_Tg.create(
                   │       └ <classmethod(<function Model.create at 0x7f5e166491b0>)>
                   └ <class 'DataBase.Models.User_Tg'>

  File "/usr/local/lib/python3.10/site-packages/tortoise/models.py", line 1135, in create
    await instance.save(using_db=db, force_create=True)
          │        │             └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x7f5e1635ff40>
          │        └ <function Model.save at 0x7f5e16648d30>
          └ <User_Tg: 180148319>
  File "/usr/local/lib/python3.10/site-packages/tortoise/models.py", line 943, in save
    await executor.execute_insert(self)
          │        │              └ <User_Tg: 180148319>
          │        └ <function BaseExecutor.execute_insert at 0x7f5e165f0ca0>
          └ <tortoise.backends.asyncpg.executor.AsyncpgExecutor object at 0x7f5e154adb40>
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/executor.py", line 234, in execute_insert
    await self.db.execute_insert(self.insert_query_all, values)
          │    │  │              │    │                 └ [180148319, 'djamka00', 'ДЛ', None, 'ru', None, None, None, datetime.datetime(2023, 2, 11, 11, 44, 14, 987492, tzinfo=<UTC>),...
          │    │  │              │    └ 'INSERT INTO "users_tg" ("id","username","first_name","last_name","lang","gender","age","advert","date_create","last_enter","...
          │    │  │              └ <tortoise.backends.asyncpg.executor.AsyncpgExecutor object at 0x7f5e154adb40>
          │    │  └ <function AsyncpgDBClient.execute_insert at 0x7f5e161393f0>
          │    └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x7f5e1635ff40>
          └ <tortoise.backends.asyncpg.executor.AsyncpgExecutor object at 0x7f5e154adb40>
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
                 │    │                     │      │       └ {}
                 │    │                     │      └ ('INSERT INTO "users_tg" ("id","username","first_name","last_name","lang","gender","age","advert","date_create","last_enter",...
                 │    │                     └ <function AsyncpgDBClient.execute_insert at 0x7f5e16139360>
                 │    └ <function AsyncpgDBClient._translate_exceptions at 0x7f5e16139120>
                 └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x7f5e1635ff40>
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 86, in _translate_exceptions
    raise IntegrityError(exc)
          └ <class 'tortoise.exceptions.IntegrityError'>

tortoise.exceptions.IntegrityError: duplicate key value violates unique constraint "users_tg_pkey"
DETAIL:  Key (id)=(180148319) already exists.
11:44:15 | ERROR | Error:
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           │    └ <function MemoryObjectReceiveStream.receive_nowait at 0x7f5e16b41870>
           └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
          └ <class 'anyio.WouldBlock'>

anyio.WouldBlock


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
                    │           └ <function MemoryObjectReceiveStream.receive at 0x7f5e16b41900>
                    └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
          └ <class 'anyio.EndOfStream'>

anyio.EndOfStream


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 9
               └ <function _main at 0x7f5e17c92440>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f5e17e656c0>
           └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f5e17e64d30>
    └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f5e17ca61d0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
    │    └ <function subprocess_started at 0x7f5e172c53f0>
    └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f5e17ca6230>>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
           │       │   │    └ <function Server.serve at 0x7f5e172c4700>
           │       │   └ <uvicorn.server.Server object at 0x7f5e17ca6230>
           │       └ <function run at 0x7f5e17c9d6c0>
           └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f5e163061f0>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f5e176ced40>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f5e176cecb0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f5e176d0820>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1899, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f5e17c341f0>
    └ <Handle <TaskStepMethWrapper object at 0x7f5e1547d150>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f5e1547d150>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f5e1547d150>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f5e1547d150>()>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f5e1635d600>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e154b7550>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e154b7550>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
                 │    └ <fastapi.applications.FastAPI object at 0x7f5e172f6350>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f5e1635d600>
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e154b7550>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e154b7550>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e154b7550>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e154b7550>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f5e1667aef0>
          └ <fastapi.applications.FastAPI object at 0x7f5e172f6350>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f5e154400d0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f5e154b7550>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f5e1667aef0>
> File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
                     │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f5e149cc9d0>
                     │    │             └ <starlette.requests.Request object at 0x7f5e153b5660>
                     │    └ <function log_middle at 0x7f5e16321bd0>
                     └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>

  File "/app/NBDapp/api_views.py", line 47, in log_middle
    response = await call_next(request)
                     │         └ <starlette.requests.Request object at 0x7f5e153b5660>
                     └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f5e149cc9d0>

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
          └ IntegrityError(UniqueViolationError('duplicate key value violates unique constraint "users_tg_pkey"'))
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
          │    │   │      │       │        │           └ <function MemoryObjectSendStream.send at 0x7f5e16b42050>
          │    │   │      │       │        └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...
          │    │   │      │       └ <property object at 0x7f5e169ae980>
          │    │   │      └ <starlette.requests.Request object at 0x7f5e153b5660>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f5e1667ba00>
          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f5e1667b820>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e149cd630>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e149cd480>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f5e1667b8b0>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f5e1667ba00>
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e149cd630>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e149cd480>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <fastapi.routing.APIRouter object at 0x7f5e172f5c60>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f5e1667b8b0>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e149cd630>
          │     │      │      └ <function set_body.<locals>.receive at 0x7f5e149cd480>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │     └ <function Route.handle at 0x7f5e167fe680>
          └ <fastapi.routing.APIRoute object at 0x7f5e16675f90>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f5e149cd630>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f5e149cd480>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.16.2', 8888), ...
          │    └ <function request_response.<locals>.app at 0x7f5e16323010>
          └ <fastapi.routing.APIRoute object at 0x7f5e16675f90>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7f5e154b77c0>
                     └ <function get_request_handler.<locals>.app at 0x7f5e16322f80>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x7f5e167fd480>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'user': {'id': 180148319, 'is_bot': False, 'first_name': 'ДЛ', 'last_name': None, 'username': 'djamka00', 'language_code': '...
                 │         └ <function user_create at 0x7f5e16322ef0>
                 └ <fastapi.dependencies.models.Dependant object at 0x7f5e16674250>

  File "/app/NBDapp/api_views.py", line 163, in user_create
    usermy = await User_Tg.create(
                   │       └ <classmethod(<function Model.create at 0x7f5e166491b0>)>
                   └ <class 'DataBase.Models.User_Tg'>

  File "/usr/local/lib/python3.10/site-packages/tortoise/models.py", line 1135, in create
    await instance.save(using_db=db, force_create=True)
          │        │             └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x7f5e1635ff40>
          │        └ <function Model.save at 0x7f5e16648d30>
          └ <User_Tg: 180148319>
  File "/usr/local/lib/python3.10/site-packages/tortoise/models.py", line 943, in save
    await executor.execute_insert(self)
          │        │              └ <User_Tg: 180148319>
          │        └ <function BaseExecutor.execute_insert at 0x7f5e165f0ca0>
          └ <tortoise.backends.asyncpg.executor.AsyncpgExecutor object at 0x7f5e1547f490>
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/executor.py", line 234, in execute_insert
    await self.db.execute_insert(self.insert_query_all, values)
          │    │  │              │    │                 └ [180148319, 'djamka00', 'ДЛ', None, 'ru', None, None, None, datetime.datetime(2023, 2, 11, 11, 44, 15, 10592, tzinfo=<UTC>), ...
          │    │  │              │    └ 'INSERT INTO "users_tg" ("id","username","first_name","last_name","lang","gender","age","advert","date_create","last_enter","...
          │    │  │              └ <tortoise.backends.asyncpg.executor.AsyncpgExecutor object at 0x7f5e1547f490>
          │    │  └ <function AsyncpgDBClient.execute_insert at 0x7f5e161393f0>
          │    └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x7f5e1635ff40>
          └ <tortoise.backends.asyncpg.executor.AsyncpgExecutor object at 0x7f5e1547f490>
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
    return await self._translate_exceptions(func, *args, **kwargs)
                 │    │                     │      │       └ {}
                 │    │                     │      └ ('INSERT INTO "users_tg" ("id","username","first_name","last_name","lang","gender","age","advert","date_create","last_enter",...
                 │    │                     └ <function AsyncpgDBClient.execute_insert at 0x7f5e16139360>
                 │    └ <function AsyncpgDBClient._translate_exceptions at 0x7f5e16139120>
                 └ <tortoise.backends.asyncpg.client.AsyncpgDBClient object at 0x7f5e1635ff40>
  File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 86, in _translate_exceptions
    raise IntegrityError(exc)
          └ <class 'tortoise.exceptions.IntegrityError'>

tortoise.exceptions.IntegrityError: duplicate key value violates unique constraint "users_tg_pkey"
DETAIL:  Key (id)=(180148319) already exists.
